CREATE TABLE products (
  product_id         text PRIMARY KEY,
  product_name       text,
  brand_id           text,
  brand_name         text,
  loves_count        integer,
  rating             numeric(3,2),
  reviews            integer,
  size               text,
  variation_type     text,
  variation_value    text,
  variation_desc     text,
  ingredients        text,
  price_usd          numeric(10,2),
  value_price_usd    numeric(10,2),
  sale_price_usd     numeric(10,2),
  limited_edition    boolean,
  new                boolean,
  online_only        boolean,
  out_of_stock       boolean,
  sephora_exclusive  boolean,
  highlights         text,
  primary_category   text,
  secondary_category text,
  tertiary_category  text,
  child_count        integer,
  child_max_price    numeric(10,2),
  child_min_price    numeric(10,2)
);
